-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, ROUND((A.DAILY_FEE * 30) * (100-C.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE and C.DURATION_TYPE = '30일 이상'
WHERE 1=1
and A.CAR_TYPE IN('세단','SUV') 
and CAR_ID NOT IN (SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE END_DATE >= '2022-11-1' and START_DATE <= '2022-11-30')
HAVING FEE >= 500000 and FEE < 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC 

