-- 코드를 입력하세요
SELECT USER_ID
        , NICKNAME
        , CONCAT(CITY," ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS "전체주소"
        , CONCAT(SUBSTRING(TLNO,1,3),"-",SUBSTRING(TLNO,4,4),"-", SUBSTRING(TLNO,8,4)) AS "전화번호"
FROM USED_GOODS_USER
WHERE USER_ID IN (SELECT U.USER_ID
                FROM USED_GOODS_USER U
                INNER JOIN USED_GOODS_BOARD B
                 ON B.WRITER_ID = U.USER_ID
                GROUP BY U.USER_ID
                 HAVING COUNT(*) >= 3)
ORDER BY USER_ID DESC