SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
WHERE ITEM_ID IN (SELECT T.ITEM_ID
                 FROM ITEM_INFO I, ITEM_TREE T
                 WHERE I.RARITY = 'RARE'
                 AND I.ITEM_ID = T.PARENT_ITEM_ID)
ORDER BY ITEM_ID DESC